language: ruby

cache: bundler

rvm:
  - 2.4.0
  - ruby-head

env:
  - DB=SQLITE
  - DB=POSTGRES
  - DB=MYSQL

gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_5.1.gemfile
  fast_finish: true

branches:
  only:
  - master

sudo: false
